/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    testimonials: Testimonial;
    media: Media;
    posts: Post;
    authors: Author;
    enquiries: Enquiry;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    authors: AuthorsSelect<false> | AuthorsSelect<true>;
    enquiries: EnquiriesSelect<false> | EnquiriesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    navigation: Navigation;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    navigation: NavigationSelect<false> | NavigationSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Site pages built from layout blocks. The page with slug "home" is the home page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  /**
   * Admin title and breadcrumb label.
   */
  title: string;
  /**
   * Page H1 for pages whose first block has no heading (text pages, blog index). Inline formatting: *italic*, **bold**, [link label](https://example.com or /path). Press Enter for a line break.
   */
  heading?: string | null;
  layout?:
    | (
        | HomeHeroBlock
        | BenefitsBlock
        | HowItWorksBlock
        | ReviewsBlock
        | FaqBlock
        | ContactOptionsBlock
        | ContactHeroBlock
        | ContactDetailsBlock
        | ContactFormBlock
        | ConfirmationBlock
        | UrgentAssistanceBlock
        | NextStepsBlock
        | AboutHeroBlock
        | TechnologyBlock
        | ExpertiseBlock
        | StatsBlock
        | CtaBannerBlock
        | RichTextBlock
      )[]
    | null;
  /**
   * Search and social sharing. Leave blank to use sensible defaults from the page content.
   */
  seo?: {
    /**
     * Shown in search results and browser tabs. Aim for 50 to 60 characters.
     */
    title?: string | null;
    /**
     * Aim for 140 to 160 characters.
     */
    description?: string | null;
    /**
     * Open Graph / Twitter image. 1200 x 630 recommended.
     */
    image?: (number | null) | Media;
    /**
     * Only set when this content lives primarily at another URL.
     */
    canonical?: string | null;
    noindex?: boolean | null;
  };
  /**
   * URL path without slashes at the ends, e.g. "about" or "terms-and-conditions". Use "home" for the home page.
   */
  slug: string;
  headerTheme: 'dark' | 'light';
  showBreadcrumbs?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HomeHeroBlock".
 */
export interface HomeHeroBlock {
  /**
   * Large H1. Example: "Fly Business." then a new line with "*Pay Insider Rates.*". Inline formatting: *italic*, **bold**, [link label](https://example.com or /path). Press Enter for a line break.
   */
  heading: string;
  subheading: string;
  /**
   * Desktop, e.g. "4.9/5.0 star rating"
   */
  ratingText: string;
  /**
   * Mobile, e.g. "5 star rating"
   */
  mobileRatingText: string;
  /**
   * Numbered steps under the heading (01, 02, 03 are added automatically).
   */
  steps: {
    label: string;
    id?: string | null;
  }[];
  /**
   * Loaded eagerly (LCP). At least 1920px wide.
   */
  image: number | Media;
  /**
   * Optional crop for phones. Falls back to the desktop image.
   */
  mobileImage?: (number | null) | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'homeHero';
}
/**
 * Images. Always write meaningful alt text; describe what the image shows for someone who cannot see it.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Alternative text for screen readers and search engines.
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    small?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BenefitsBlock".
 */
export interface BenefitsBlock {
  items: {
    /**
     * SVG icon.
     */
    icon: number | Media;
    /**
     * Inline formatting: *italic*, **bold**, [link label](https://example.com or /path). Press Enter for a line break.
     */
    title: string;
    text: string;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'benefits';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HowItWorksBlock".
 */
export interface HowItWorksBlock {
  /**
   * Inline formatting: *italic*, **bold**, [link label](https://example.com or /path). Press Enter for a line break.
   */
  heading: string;
  cards: {
    title: string;
    text: string;
    /**
     * What the card shows above its text.
     */
    visual: 'image' | 'options' | 'checkout';
    /**
     * Used when Visual is "Photo".
     */
    image?: (number | null) | Media;
    id?: string | null;
  }[];
  /**
   * Round rotating badge linking to the quote form.
   */
  badge: {
    /**
     * e.g. "Get *Flight*\nOptions" Inline formatting: *italic*, **bold**, [link label](https://example.com or /path). Press Enter for a line break.
     */
    label: string;
    /**
     * Site path (/about/), #anchor, full URL, mailto: or tel:
     */
    href: string;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'howItWorks';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ReviewsBlock".
 */
export interface ReviewsBlock {
  /**
   * Inline formatting: *italic*, **bold**, [link label](https://example.com or /path). Press Enter for a line break.
   */
  heading: string;
  /**
   * e.g. "Excellent | Rated 4.9/5.0"
   */
  ratingLabel: string;
  /**
   * Optional. Leave empty to show the newest approved 5-star reviews automatically (synced Trustpilot reviews first, by date). Pick testimonials here to show exactly these, in this order, instead.
   */
  testimonials?: (number | Testimonial)[] | null;
  /**
   * How many reviews to show when none are pinned (default 8).
   */
  limit?: number | null;
  airlines: number | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'reviews';
}
/**
 * Customer reviews. Trustpilot reviews sync in daily as "not approved": tick Approved (in the list or the review) to allow one on the site. Reviews blocks show the newest approved 5-star reviews unless the block pins specific ones.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  /**
   * Reviewer name as shown.
   */
  name: string;
  rating: number;
  /**
   * Lower numbers first (reviews without a date).
   */
  order?: number | null;
  /**
   * Review headline.
   */
  title: string;
  /**
   * Required for manual reviews. The site shows up to about 400 characters per card.
   */
  body?: string | null;
  /**
   * Shown on the site. Synced Trustpilot reviews start unticked.
   */
  approved?: boolean | null;
  source: 'manual' | 'trustpilot';
  /**
   * Newest first on the site.
   */
  reviewDate?: string | null;
  /**
   * Trustpilot review id (set by the sync). Leave empty for manual reviews.
   */
  reviewId?: string | null;
  /**
   * Last time the Trustpilot sync sent this review.
   */
  lastSyncedAt?: string | null;
  /**
   * Link to the review on Trustpilot.
   */
  reviewUrl?: string | null;
  country?: string | null;
  language?: string | null;
  replyText?: string | null;
  /**
   * The review exactly as the scraper sent it. Not public.
   */
  raw?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FaqBlock".
 */
export interface FaqBlock {
  /**
   * Inline formatting: *italic*, **bold**, [link label](https://example.com or /path). Press Enter for a line break.
   */
  heading: string;
  items: {
    question: string;
    answer: string;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'faq';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContactOptionsBlock".
 */
export interface ContactOptionsBlock {
  /**
   * Optional section heading. Inline formatting: *italic*, **bold**, [link label](https://example.com or /path). Press Enter for a line break.
   */
  heading?: string | null;
  /**
   * One card per contact channel.
   */
  cards: {
    icon: 'phone' | 'email' | 'whatsapp';
    title: string;
    /**
     * Inline formatting: *italic*, **bold**, [link label](https://example.com or /path). Press Enter for a line break.
     */
    body: string;
    linkLabel: string;
    /**
     * tel:, mailto:, https:// or a path
     */
    linkUrl: string;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'contactOptions';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContactHeroBlock".
 */
export interface ContactHeroBlock {
  /**
   * Inline formatting: *italic*, **bold**, [link label](https://example.com or /path). Press Enter for a line break.
   */
  heading: string;
  subheading: string;
  body: string;
  image: number | Media;
  /**
   * Optional crop for phones.
   */
  mobileImage?: (number | null) | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'contactHero';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContactDetailsBlock".
 */
export interface ContactDetailsBlock {
  items: {
    label: string;
    /**
     * Phone and email rows read Site settings > Contact. The email row follows the Sales / Support choice on the contact form.
     */
    source: 'custom' | 'salesPhone' | 'supportPhone' | 'email';
    value?: string | null;
    /**
     * tel:, mailto: or URL
     */
    href?: string | null;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'contactDetails';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContactFormBlock".
 */
export interface ContactFormBlock {
  /**
   * Button text.
   */
  submitLabel: string;
  /**
   * Small print under the form.
   */
  note: string;
  /**
   * Optional contact details card shown beside the form (left column on desktop, above the form on mobile). The form has a Sales / Support inquiry choice that swaps the email row and highlights the matching phone row.
   */
  details?:
    | {
        label: string;
        /**
         * Phone and email rows read Site settings > Contact. The email row follows the Sales / Support choice on the contact form.
         */
        source: 'custom' | 'salesPhone' | 'supportPhone' | 'email';
        value?: string | null;
        /**
         * tel:, mailto: or URL
         */
        href?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'contactForm';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ConfirmationBlock".
 */
export interface ConfirmationBlock {
  /**
   * Inline formatting: *italic*, **bold**, [link label](https://example.com or /path). Press Enter for a line break.
   */
  heading: string;
  subheading: string;
  body: string;
  /**
   * Button under the message.
   */
  button: {
    label: string;
    /**
     * Site path (/about/), #anchor, full URL, mailto: or tel:
     */
    href: string;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'confirmation';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "UrgentAssistanceBlock".
 */
export interface UrgentAssistanceBlock {
  /**
   * Inline formatting: *italic*, **bold**, [link label](https://example.com or /path). Press Enter for a line break.
   */
  heading: string;
  body: string;
  image: number | Media;
  /**
   * Optional crop for phones.
   */
  mobileImage?: (number | null) | Media;
  /**
   * Contact channels shown on the panel.
   */
  cards: {
    icon: 'phone' | 'email' | 'whatsapp';
    title: string;
    /**
     * Inline formatting: *italic*, **bold**, [link label](https://example.com or /path). Press Enter for a line break.
     */
    body: string;
    linkLabel: string;
    /**
     * tel:, mailto:, https:// or a path
     */
    linkUrl: string;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'urgentAssistance';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "NextStepsBlock".
 */
export interface NextStepsBlock {
  /**
   * Inline formatting: *italic*, **bold**, [link label](https://example.com or /path). Press Enter for a line break.
   */
  heading: string;
  steps: {
    title: string;
    text: string;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'nextSteps';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AboutHeroBlock".
 */
export interface AboutHeroBlock {
  /**
   * Inline formatting: *italic*, **bold**, [link label](https://example.com or /path). Press Enter for a line break.
   */
  heading: string;
  /**
   * Inline formatting: *italic*, **bold**, [link label](https://example.com or /path). Press Enter for a line break.
   */
  body: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'aboutHero';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TechnologyBlock".
 */
export interface TechnologyBlock {
  /**
   * Small line above the heading, e.g. "Expertise, amplified".
   */
  eyebrow?: string | null;
  /**
   * e.g. "Our people, *powered by AI*". Inline formatting: *italic*, **bold**, [link label](https://example.com or /path). Press Enter for a line break.
   */
  heading: string;
  intro?: string | null;
  items: {
    icon: 'ai-search' | 'ai-route' | 'ai-watch' | 'ai-expert';
    title: string;
    text: string;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'technology';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ExpertiseBlock".
 */
export interface ExpertiseBlock {
  /**
   * Inline formatting: *italic*, **bold**, [link label](https://example.com or /path). Press Enter for a line break.
   */
  heading: string;
  image: number | Media;
  items: {
    title: string;
    text: string;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'expertise';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StatsBlock".
 */
export interface StatsBlock {
  items: {
    /**
     * SVG icon.
     */
    icon: number | Media;
    /**
     * Bold stat title, e.g. "90% Client Retention". Inline formatting: *italic*, **bold**, [link label](https://example.com or /path). Press Enter for a line break.
     */
    label: string;
    /**
     * Supporting line (desktop and tablet only).
     */
    text?: string | null;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'stats';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CtaBannerBlock".
 */
export interface CtaBannerBlock {
  /**
   * Inline formatting: *italic*, **bold**, [link label](https://example.com or /path). Press Enter for a line break.
   */
  heading: string;
  /**
   * A new line forces a line break. Inline formatting: *italic*, **bold**, [link label](https://example.com or /path). Press Enter for a line break.
   */
  body: string;
  primary: {
    label: string;
    /**
     * Site path (/about/), #anchor, full URL, mailto: or tel:
     */
    href: string;
  };
  secondary: {
    label: string;
    /**
     * Site path (/about/), #anchor, full URL, mailto: or tel:
     */
    href: string;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'ctaBanner';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RichTextBlock".
 */
export interface RichTextBlock {
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'richText';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  /**
   * Shown on blog cards and as the default meta description.
   */
  excerpt: string;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Top of the article. At least 1600px wide.
   */
  heroImage: number | Media;
  /**
   * Optional different crop for blog cards.
   */
  cardImage?: (number | null) | Media;
  art?: {
    /**
     * Region of the card image shown in the 3:2 blog card, as % of the image: top-left X / Y and width (100 = full width). Leave empty for no crop.
     */
    cardCrop?: {
      x?: number | null;
      y?: number | null;
      w?: number | null;
    };
    cardShade?: boolean | null;
    /**
     * CSS object-position, e.g. "100% 71%". Applied before mirroring.
     */
    heroPosition?: string | null;
    heroMirror?: boolean | null;
  };
  /**
   * Search and social sharing. Leave blank to use sensible defaults from the page content.
   */
  seo?: {
    /**
     * Shown in search results and browser tabs. Aim for 50 to 60 characters.
     */
    title?: string | null;
    /**
     * Aim for 140 to 160 characters.
     */
    description?: string | null;
    /**
     * Open Graph / Twitter image. 1200 x 630 recommended.
     */
    image?: (number | null) | Media;
    /**
     * Only set when this content lives primarily at another URL.
     */
    canonical?: string | null;
    noindex?: boolean | null;
  };
  /**
   * URL segment. Generated from the title if left empty. Lowercase letters, numbers and hyphens.
   */
  slug: string;
  author: number | Author;
  publishedAt: string;
  /**
   * Minutes. Calculated from the content if left empty.
   */
  readTime: number;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors".
 */
export interface Author {
  id: number;
  name: string;
  /**
   * e.g. "Senior Travel Consultant"
   */
  role: string;
  /**
   * URL segment. Generated from the title if left empty. Lowercase letters, numbers and hyphens.
   */
  slug: string;
  photo: number | Media;
  bioIntro: string;
  /**
   * Optional pull quote on the author page.
   */
  quote?: string | null;
  /**
   * Optional second part of the bio.
   */
  bioMore?: string | null;
  expertise: {
    label: string;
    id?: string | null;
  }[];
  linkedin?: string | null;
  x?: string | null;
  /**
   * Search and social sharing. Leave blank to use sensible defaults from the page content.
   */
  seo?: {
    /**
     * Shown in search results and browser tabs. Aim for 50 to 60 characters.
     */
    title?: string | null;
    /**
     * Aim for 140 to 160 characters.
     */
    description?: string | null;
    /**
     * Open Graph / Twitter image. 1200 x 630 recommended.
     */
    image?: (number | null) | Media;
    /**
     * Only set when this content lives primarily at another URL.
     */
    canonical?: string | null;
    noindex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Quote requests, contact messages and live chat leads from the website. Update the status as you work each lead.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enquiries".
 */
export interface Enquiry {
  id: number;
  displayName?: string | null;
  kind: 'quote' | 'contact' | 'chat';
  /**
   * Sales or support (contact form).
   */
  topic?: ('sales' | 'support') | null;
  tripType?: ('round-trip' | 'one-way' | 'multi-city') | null;
  cabin?: ('business' | 'first' | 'premium-economy' | 'economy') | null;
  /**
   * Flight 1 is the outbound flight.
   */
  legs?:
    | {
        from?: string | null;
        to?: string | null;
        date?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Round trips only.
   */
  returnDate?: string | null;
  travellers?: {
    adults?: number | null;
    children?: number | null;
    infants?: number | null;
  };
  /**
   * Quote form (single name field).
   */
  name?: string | null;
  firstName?: string | null;
  lastName?: string | null;
  email?: string | null;
  phone?: string | null;
  subject?: string | null;
  message?: string | null;
  smsConsent?: boolean | null;
  pageUrl?: string | null;
  status: 'new' | 'contacted' | 'quoted' | 'booked' | 'closed';
  notes?: string | null;
  meta?: {
    ip?: string | null;
    userAgent?: string | null;
    origin?: string | null;
    crmStatus?: ('pending' | 'sent' | 'failed' | 'skipped') | null;
    crmError?: string | null;
    /**
     * e.g. jivo:<chat id> (prevents duplicates from webhook retries).
     */
    externalId?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'authors';
        value: number | Author;
      } | null)
    | ({
        relationTo: 'enquiries';
        value: number | Enquiry;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  heading?: T;
  layout?:
    | T
    | {
        homeHero?: T | HomeHeroBlockSelect<T>;
        benefits?: T | BenefitsBlockSelect<T>;
        howItWorks?: T | HowItWorksBlockSelect<T>;
        reviews?: T | ReviewsBlockSelect<T>;
        faq?: T | FaqBlockSelect<T>;
        contactOptions?: T | ContactOptionsBlockSelect<T>;
        contactHero?: T | ContactHeroBlockSelect<T>;
        contactDetails?: T | ContactDetailsBlockSelect<T>;
        contactForm?: T | ContactFormBlockSelect<T>;
        confirmation?: T | ConfirmationBlockSelect<T>;
        urgentAssistance?: T | UrgentAssistanceBlockSelect<T>;
        nextSteps?: T | NextStepsBlockSelect<T>;
        aboutHero?: T | AboutHeroBlockSelect<T>;
        technology?: T | TechnologyBlockSelect<T>;
        expertise?: T | ExpertiseBlockSelect<T>;
        stats?: T | StatsBlockSelect<T>;
        ctaBanner?: T | CtaBannerBlockSelect<T>;
        richText?: T | RichTextBlockSelect<T>;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        canonical?: T;
        noindex?: T;
      };
  slug?: T;
  headerTheme?: T;
  showBreadcrumbs?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HomeHeroBlock_select".
 */
export interface HomeHeroBlockSelect<T extends boolean = true> {
  heading?: T;
  subheading?: T;
  ratingText?: T;
  mobileRatingText?: T;
  steps?:
    | T
    | {
        label?: T;
        id?: T;
      };
  image?: T;
  mobileImage?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BenefitsBlock_select".
 */
export interface BenefitsBlockSelect<T extends boolean = true> {
  items?:
    | T
    | {
        icon?: T;
        title?: T;
        text?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HowItWorksBlock_select".
 */
export interface HowItWorksBlockSelect<T extends boolean = true> {
  heading?: T;
  cards?:
    | T
    | {
        title?: T;
        text?: T;
        visual?: T;
        image?: T;
        id?: T;
      };
  badge?:
    | T
    | {
        label?: T;
        href?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ReviewsBlock_select".
 */
export interface ReviewsBlockSelect<T extends boolean = true> {
  heading?: T;
  ratingLabel?: T;
  testimonials?: T;
  limit?: T;
  airlines?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FaqBlock_select".
 */
export interface FaqBlockSelect<T extends boolean = true> {
  heading?: T;
  items?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContactOptionsBlock_select".
 */
export interface ContactOptionsBlockSelect<T extends boolean = true> {
  heading?: T;
  cards?:
    | T
    | {
        icon?: T;
        title?: T;
        body?: T;
        linkLabel?: T;
        linkUrl?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContactHeroBlock_select".
 */
export interface ContactHeroBlockSelect<T extends boolean = true> {
  heading?: T;
  subheading?: T;
  body?: T;
  image?: T;
  mobileImage?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContactDetailsBlock_select".
 */
export interface ContactDetailsBlockSelect<T extends boolean = true> {
  items?:
    | T
    | {
        label?: T;
        source?: T;
        value?: T;
        href?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContactFormBlock_select".
 */
export interface ContactFormBlockSelect<T extends boolean = true> {
  submitLabel?: T;
  note?: T;
  details?:
    | T
    | {
        label?: T;
        source?: T;
        value?: T;
        href?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ConfirmationBlock_select".
 */
export interface ConfirmationBlockSelect<T extends boolean = true> {
  heading?: T;
  subheading?: T;
  body?: T;
  button?:
    | T
    | {
        label?: T;
        href?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "UrgentAssistanceBlock_select".
 */
export interface UrgentAssistanceBlockSelect<T extends boolean = true> {
  heading?: T;
  body?: T;
  image?: T;
  mobileImage?: T;
  cards?:
    | T
    | {
        icon?: T;
        title?: T;
        body?: T;
        linkLabel?: T;
        linkUrl?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "NextStepsBlock_select".
 */
export interface NextStepsBlockSelect<T extends boolean = true> {
  heading?: T;
  steps?:
    | T
    | {
        title?: T;
        text?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AboutHeroBlock_select".
 */
export interface AboutHeroBlockSelect<T extends boolean = true> {
  heading?: T;
  body?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TechnologyBlock_select".
 */
export interface TechnologyBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  intro?: T;
  items?:
    | T
    | {
        icon?: T;
        title?: T;
        text?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ExpertiseBlock_select".
 */
export interface ExpertiseBlockSelect<T extends boolean = true> {
  heading?: T;
  image?: T;
  items?:
    | T
    | {
        title?: T;
        text?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StatsBlock_select".
 */
export interface StatsBlockSelect<T extends boolean = true> {
  items?:
    | T
    | {
        icon?: T;
        label?: T;
        text?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CtaBannerBlock_select".
 */
export interface CtaBannerBlockSelect<T extends boolean = true> {
  heading?: T;
  body?: T;
  primary?:
    | T
    | {
        label?: T;
        href?: T;
      };
  secondary?:
    | T
    | {
        label?: T;
        href?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RichTextBlock_select".
 */
export interface RichTextBlockSelect<T extends boolean = true> {
  content?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  name?: T;
  rating?: T;
  order?: T;
  title?: T;
  body?: T;
  approved?: T;
  source?: T;
  reviewDate?: T;
  reviewId?: T;
  lastSyncedAt?: T;
  reviewUrl?: T;
  country?: T;
  language?: T;
  replyText?: T;
  raw?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        small?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  excerpt?: T;
  content?: T;
  heroImage?: T;
  cardImage?: T;
  art?:
    | T
    | {
        cardCrop?:
          | T
          | {
              x?: T;
              y?: T;
              w?: T;
            };
        cardShade?: T;
        heroPosition?: T;
        heroMirror?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        canonical?: T;
        noindex?: T;
      };
  slug?: T;
  author?: T;
  publishedAt?: T;
  readTime?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors_select".
 */
export interface AuthorsSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  slug?: T;
  photo?: T;
  bioIntro?: T;
  quote?: T;
  bioMore?: T;
  expertise?:
    | T
    | {
        label?: T;
        id?: T;
      };
  linkedin?: T;
  x?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        canonical?: T;
        noindex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enquiries_select".
 */
export interface EnquiriesSelect<T extends boolean = true> {
  displayName?: T;
  kind?: T;
  topic?: T;
  tripType?: T;
  cabin?: T;
  legs?:
    | T
    | {
        from?: T;
        to?: T;
        date?: T;
        id?: T;
      };
  returnDate?: T;
  travellers?:
    | T
    | {
        adults?: T;
        children?: T;
        infants?: T;
      };
  name?: T;
  firstName?: T;
  lastName?: T;
  email?: T;
  phone?: T;
  subject?: T;
  message?: T;
  smsConsent?: T;
  pageUrl?: T;
  status?: T;
  notes?: T;
  meta?:
    | T
    | {
        ip?: T;
        userAgent?: T;
        origin?: T;
        crmStatus?: T;
        crmError?: T;
        externalId?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Contact details, trust badges and footer content used across the site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  phone: {
    /**
     * e.g. "(888) 855-2389"
     */
    display: string;
    /**
     * e.g. "tel:+18888552389"
     */
    href: string;
  };
  /**
   * International format for the footer, e.g. "+1 (888) 855-2389".
   */
  phoneFull: string;
  /**
   * Contact page details card ("Sales Line" row) and the Sales inquiry option.
   */
  salesPhone: {
    /**
     * e.g. "(888) 855-2389"
     */
    display: string;
    /**
     * e.g. "tel:+18888552389"
     */
    href: string;
  };
  /**
   * Contact page details card ("Customer Support" row) and the Support inquiry option.
   */
  supportPhone: {
    /**
     * e.g. "(888) 855-2389"
     */
    display: string;
    /**
     * e.g. "tel:+18888552389"
     */
    href: string;
  };
  /**
   * Shown on the Contact page when "Sales inquiry" is selected.
   */
  salesEmail: string;
  /**
   * Shown on the Contact page when "Support inquiry" is selected.
   */
  supportEmail: string;
  /**
   * Customer service email.
   */
  email: string;
  /**
   * New enquiries email.
   */
  enquiriesEmail: string;
  address: string;
  /**
   * e.g. https://wa.me/18888552389
   */
  whatsappUrl: string;
  /**
   * Leave empty to hide an icon.
   */
  socials?: {
    facebook?: string | null;
    linkedin?: string | null;
    instagram?: string | null;
  };
  /**
   * Small label above the header phone number, e.g. "24/7 PHONE DEALS".
   */
  headerPhoneLabel: string;
  /**
   * Floating "call us" pill.
   */
  callPill: {
    title: string;
    subtitle: string;
  };
  /**
   * Contact lines at the bottom of the hamburger menu.
   */
  menuContacts?:
    | {
        label: string;
        value: string;
        /**
         * tel:, mailto: or URL
         */
        href: string;
        id?: string | null;
      }[]
    | null;
  trustpilot: {
    /**
     * e.g. "4.9/5.0"
     */
    rating: string;
    url?: string | null;
  };
  accreditations?:
    | {
        name: string;
        url?: string | null;
        logo: number | Media;
        id?: string | null;
      }[]
    | null;
  paymentMethods: number | Media;
  footerVision: string;
  copyright: string;
  /**
   * Small-print paragraphs at the bottom of every page.
   */
  disclaimerItems?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  disclaimers?: string[] | null;
  /**
   * One line under the quote form and contact form buttons (contact consent + privacy). Have counsel review changes. Inline formatting: *italic*, **bold**, [link label](https://example.com or /path). Press Enter for a line break.
   */
  consentNote: string;
  /**
   * The round chat button (mobile). "None": it opens a small panel with WhatsApp, call and the quote form. "Jivo": it loads and opens the Jivo chat (setup steps in apps/cms/README.md).
   */
  chat: {
    provider: 'none' | 'jivo';
    /**
     * From the install code: //code.jivosite.com/widget/<ID>
     */
    jivoWidgetId?: string | null;
    /**
     * Used to label the chat button "Chat now" or "Leave a message" before Jivo has loaded. Agent schedules themselves are set per agent in Jivo.
     */
    businessHours?: {
      /**
       * IANA name, e.g. America/Chicago
       */
      timezone?: string | null;
      /**
       * 24h, e.g. 08:00
       */
      open?: string | null;
      /**
       * 24h, e.g. 20:00 (23:59 = midnight)
       */
      close?: string | null;
      days?: ('mon' | 'tue' | 'wed' | 'thu' | 'fri' | 'sat' | 'sun')[] | null;
    };
    /**
     * Optional line in the built-in chat panel.
     */
    note?: string | null;
  };
  /**
   * Banner at the end of blog articles.
   */
  blogCta: {
    /**
     * Inline formatting: *italic*, **bold**, [link label](https://example.com or /path). Press Enter for a line break.
     */
    heading: string;
    body: string;
    primaryLabel: string;
    secondaryLabel: string;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  /**
   * Hamburger menu items.
   */
  menu?:
    | {
        label: string;
        /**
         * Site path (/about/), #anchor, full URL, mailto: or tel:
         */
        href: string;
        id?: string | null;
      }[]
    | null;
  footer?:
    | {
        label: string;
        /**
         * Site path (/about/), #anchor, full URL, mailto: or tel:
         */
        href: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  phone?:
    | T
    | {
        display?: T;
        href?: T;
      };
  phoneFull?: T;
  salesPhone?:
    | T
    | {
        display?: T;
        href?: T;
      };
  supportPhone?:
    | T
    | {
        display?: T;
        href?: T;
      };
  salesEmail?: T;
  supportEmail?: T;
  email?: T;
  enquiriesEmail?: T;
  address?: T;
  whatsappUrl?: T;
  socials?:
    | T
    | {
        facebook?: T;
        linkedin?: T;
        instagram?: T;
      };
  headerPhoneLabel?: T;
  callPill?:
    | T
    | {
        title?: T;
        subtitle?: T;
      };
  menuContacts?:
    | T
    | {
        label?: T;
        value?: T;
        href?: T;
        id?: T;
      };
  trustpilot?:
    | T
    | {
        rating?: T;
        url?: T;
      };
  accreditations?:
    | T
    | {
        name?: T;
        url?: T;
        logo?: T;
        id?: T;
      };
  paymentMethods?: T;
  footerVision?: T;
  copyright?: T;
  disclaimerItems?:
    | T
    | {
        text?: T;
        id?: T;
      };
  disclaimers?: T;
  consentNote?: T;
  chat?:
    | T
    | {
        provider?: T;
        jivoWidgetId?: T;
        businessHours?:
          | T
          | {
              timezone?: T;
              open?: T;
              close?: T;
              days?: T;
            };
        note?: T;
      };
  blogCta?:
    | T
    | {
        heading?: T;
        body?: T;
        primaryLabel?: T;
        secondaryLabel?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  menu?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  footer?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}